# Set environment
library(shiny)
library(ggplot2)
library(sf)
library(sp)
library(dplyr)
library(readxl)
library(leaflet)
library(leafpop)
library(showtext)
library(shinyalert)
library(mapview)
library(shinycssloaders)
library(xts)
library(TSstudio)
library(tidyr)
library(plotly)